# Generated by Django 4.2.10 on 2025-02-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testapp',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='testapp',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='testapp',
            index=models.Index(fields=['-time_create'], name='testApp_tes_time_cr_77222b_idx'),
        ),
    ]
