# Generated by Django 4.2.10 on 2025-02-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_alter_testapp_options_testapp_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapp',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
