# Generated by Django 4.2.10 on 2025-02-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_alter_testapp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapp',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
