# Generated by Django 4.2.10 on 2025-02-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_category_testapp_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapp',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testApp.category'),
        ),
    ]
