# Generated by Django 4.2.10 on 2025-02-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_tagpost_alter_testapp_cat_testapp_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_code', models.CharField(max_length=25)),
                ('guitar_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='testapp',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='testApp.article'),
        ),
    ]
