# Generated by Django 4.2.10 on 2025-02-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_article_testapp_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='testapp',
            name='view_count',
            field=models.IntegerField(blank='True', default=0),
        ),
    ]
