# Generated by Django 4.2.10 on 2025-02-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_testapp_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='testapp',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Гитары', 'verbose_name_plural': 'Гитары'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='testapp',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='testApp.article', verbose_name='Код артикула'),
        ),
        migrations.AlterField(
            model_name='testapp',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='testApp.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='testapp',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст описания'),
        ),
        migrations.AlterField(
            model_name='testapp',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус публикации'),
        ),
        migrations.AlterField(
            model_name='testapp',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='testApp.tagpost', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='testapp',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='testapp',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='testapp',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
