# Generated by Django 4.2.10 on 2025-02-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_alter_category_options_alter_testapp_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
    ]
