# Generated by Django 4.2.10 on 2025-02-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0011_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='testapp',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
